language: scala
scala:
   2.11.8

jdk:
  - oraclejdk8

# only trigger builds on master
branches:
  only:
    - master
    - 2.0.x

# start the couchdb service (runs in admin party)
services: couchdb

script:
  - sbt clean coverage test coverageReport coverageAggregate

# create an admin user
before_script:
  - curl -X PUT -d '"true"' localhost:5984/_config/couch_httpd_oauth/use_users_db
  - curl -X PUT -d '"admin"' localhost:5984/_config/admins/admin
  - echo 'testOptions in Test += Tests.Argument(TestFrameworks.ScalaTest, "-l", "org.gnieh.sohva.NoTravis")' > local.sbt
# optional: create a user document...  - curl -X PUT -d '{ "_id": "org.couchdb.user:admin", "password": null, "name": "admin", "roles": [], "type": "user" }' localhost:5984/_users/org.couchdb.user:admin

after_success:
 - bash <(curl -s https://codecov.io/bash)
